database:
  image: "postgres:14.10"
  resources:
    cpuLimit: 1
    memoryLimit: 1Gi
    cpuRequest: 100m
    memoryRequest: 256Mi
    storage: 5Gi
  config:
    db: app
    schema: app
    port: 5432
    dialect: postgres
    username: postgres
    password: postgres
    mountPath: /var/lib/postgresql/data
  migration:
    image: "mahithchigurupati/webapp-db:latest"
    mountPath: /flyway/sql
  

webapp:
  image: "mahithchigurupati/webapp-gcp:latest"
  resources:
    cpuLimit: 1
    memoryLimit: 512Mi
    cpuRequest: 100m
    memoryRequest: 256Mi
  service:
    type: LoadBalancer
  port: 8080

deployment:
  strategy: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  replicas: 1
  minReadySeconds: 30
  progressDeadlineSeconds: 120


