apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.config.db | toYaml | b64enc }}
  POSTGRES_USER: {{ .Values.database.config.username | toYaml | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.config.password | toYaml | b64enc }}