apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
  labels:
    app: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: {{ .Values.database.config.port }}
      targetPort: {{ .Values.database.config.port }}
