apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webapp-secret
type: Opaque
data:
  FLYWAY_USER: {{ .Values.database.config.username | toYaml | b64enc }}
  FLYWAY_PASSWORD: {{ .Values.database.config.password | toYaml | b64enc }}
  FLYWAY_SCHEMAS: {{ .Values.database.config.schema | toYaml | b64enc }}
  