apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-webapp-service
  name: {{ .Release.Name }}-webapp-service
spec:
  selector:
    app: {{ .Release.Name }}-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.webapp.port }}

  type: {{ .Values.webapp.service.type }}
